spring:
  profiles:
    active: local   # 기본 활성화

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/${DB_NAME}}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # 배치 서버는 스키마 변경 금지
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: never   # schema.sql로 직접 관리
  sql:
    init:
      mode: always  # Boot 2.5+ 환경에서 필요, schema.sql 실행

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
          max-wait: -1ms

server:
  port: 8081
